2015-10-02 14:51:52,851 - aee    - INFO    : Creating mongodb record with run id 2015-10-02_14:51:52.851361_DE_favorites_spider
2015-10-02 14:51:54,865 - aee    - INFO    : started crawl with run id: 2015-10-02_14:51:52.851361_DE_favorites_spider
2015-10-02 14:51:54,866 - aee    - INFO    : 1 Instances will be launched for 2 dockets of state DE
2015-10-02 14:52:21,782 - aee    - INFO    : Starting Scheduler for crawl type: favorites
2015-10-02 14:52:21,782 - aee    - INFO    : spawning instance
2015-10-02 14:52:21,783 - aee    - INFO    : saving ansible launch script log in file: 2015-10-02 14:52:21_782837.txt
2015-10-02 14:54:57,789 - aee    - INFO    : Instance spawned with ip: 54.174.83.75
2015-10-02 14:54:57,789 - aee    - INFO    : Time Taken to spawn instance: 0:02:36.007338
2015-10-02 14:54:57,790 - aee    - INFO    : Creating Temp project directory in path /Users/omairshamshir/distributed_weekly_crawl_temp/adf9b426e13d4db7933266d12525bea7
2015-10-02 14:55:01,906 - aee    - INFO    : Adding Instance ip to redis
2015-10-02 14:55:03,477 - aee    - INFO    : Adding the ip of the instance to scrapy.cfg
Traceback (most recent call last):
  File "/Users/omairshamshir/Documents/github/puctools/bin/instance_scheduler.py", line 241, in <module>
    main()
  File "/Users/omairshamshir/Documents/github/puctools/bin/instance_scheduler.py", line 210, in main
    update_scrapy_cfg(scrapyd_url, proj_path)
  File "/Users/omairshamshir/Documents/github/puctools/bin/instance_scheduler.py", line 70, in update_scrapy_cfg
    for line in fileinput.input(scrapy_cfg_path, inplace=1):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fileinput.py", line 252, in next
    line = self.readline()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fileinput.py", line 321, in readline
    os.rename(self._filename, self._backupfilename)
OSError: [Errno 2] No such file or directory
